### ISSUE TITLE
As an app user, I want a dark mode so I can reduce eye strain

### ISSUE THREAD

**Issue by danbenn** [STEPBible/BibleEngine#107]
this requires editing the styles of almost every component, which is a bit painful

**Comment by bobokeke0** [comment]
perhaps updating react navigations can help take advantage of easy styling.
I recommend someone (I'll see if I have time) take some burden off the developer and create a PR with some updates and styling help.

**Comment by patrickxchong** [comment]
Hey @bobokeke0 , we've worked on the feature and have merged it into the development branch, you can refer to #199 for more details. Sorry for not updating this issue with that. It'll be out in the next release within a couple of month!
