### ISSUE TITLE
Mac step.dmg installation error

### ISSUE THREAD

**Issue by markcannon-step** [STEPBible/BibleEngine#166]
In FST-1596 a user indicated, "Mac will not allow the installer to go through because it can't check it for "malicious software", it says to contact the developer for an update."
It looks like the dmg needs to be signed with an authorized developer certificate if I have the wording correct. We saw this occasionally with new updates to the Mac Installer dmg for BibleWorks.
I confirmed the bug by testing with an attempted installation on my wife's Mac. See the attached screenshots.
![Mac Error STEP dmg](https://user-images.githubusercontent.com/66133976/83317879-41725b00-a1fe-11ea-8da5-0ea040f9d268.jpg)
![STEP dmg](https://user-images.githubusercontent.com/66133976/83317883-46cfa580-a1fe-11ea-86e7-5ed38e36e4e2.jpg)

**Comment by DavidIB** [comment]
Thanks Mark. 

It looks like this concerns the Download version of www.STEPBIble.org <http://www.STEPBIble.org> , not BibleEngine or the mobile version

We have a certificate, though I’m not sure I know how to apply it to Mac dmg.

I’ll have to look into it.

Glad to know you are able to check it. 

 

David IB
