### ISSUE TITLE
Jesus' Words in Red option disables hyperlink of words

### ISSUE THREAD

**Issue by markcannon-step** [STEPBible/BibleEngine#173]
To reproduce, viewing a gospel passage in the ESV, click on the Options button and turn on Jesus' words in red. Now try to mouse over any of the words that are now red and you will find that the hyperlink for information on the word does not work.
MC, 11/9/2020
Reported in https://stepweb.atlassian.net/browse/FST-1639

**Comment by danbenn** [comment]
@markcannon-step I think this is for the desktop site: https://github.com/stepbible/step
