### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by nikitazdvijkov** [STEPBible/BibleEngine#197]
Broken link to the "excellent datasets of Tyndale House" in README under "About BibleEngine" section.

Original:

[`https://tyndale.github.io/STEPBible-Data/`](https://tyndale.github.io/STEPBible-Data/)

Should be(?):

[`https://stepbible.github.io/STEPBible-Data/`](https://stepbible.github.io/STEPBible-Data/)

**Comment by DavidIB** [comment]
Thanks for reporting this important issue.
*David IB*

**Comment by danbenn** [comment]
@nikitazdvijkov, thank you for reporting. This is now fixed ✅
