### ISSUE TITLE
Importers require Json that is not shipped with NPM package

### ISSUE THREAD

**Issue by julianwagle** [STEPBible/BibleEngine#207]
The following file links to JSON that is not shipped with the package: 

https://github.com/STEPBible/BibleEngine/blob/master/importers/src/bible/sword/src/VerseScheme.ts#L1

As a result, all functions that pull from the file throw an error. 

i.e. `creator.addImporter(V11nImporter);`

This is part of a much much larger problem with the code base - it uses pretty bad linting practices, a require statement should have never made it in the code in the first place. (https://typescript-eslint.io/rules/no-require-imports) 

I would strongly recommend adding in typescript-eslint with all it's recommendations to avoid these and many many more errors that are waiting to cause you long nights of frustration. I'd be happy to take the charge on that if you guys are interested - i love the project and would be happy to help.

I went ahead and added typescript-eslint to see what kind of results it gave me after running a quick lint:

```
✖ 861 problems (84 errors, 777 warnings)
  22 errors and 115 warnings potentially fixable with the `--fix` option.
```

Needless to say this would be pretty time consuming to fix but it would be in the best interest of the project & well worth the time.

**Comment by danbenn** [comment]
Hi @julianwagle , thanks for reaching out! I filled out your Calendly form, let's meet sometime and explore some options!

**Comment by julianwagle** [comment]
Nice, thanks for taking the initiative that far! I like the time you selected, I look forward to meeting!
